[package]
name = "gdbloader"
version = "0.1.1"
edition = "2021"

[dependencies]
log = "0.4.24"
env_logger = "0.11.6"

thiserror = "2.0.11"
anyhow = "1"

tokio = { version = "1.43.0", features = ["full"] }

regex = "1.11.1"
clap = { version = "4.5.31", features = ["derive"] }